update EditMenuProductFragment.kt
xidealo/FoodDeliveryAdmin pull request #13
Opened 2023-06-18 10:40 UTC by xidealo

2023-08-15 21:31 UTC, MaxAstin requested changes

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/main/java/com/bunbeauty/domain/feature/order_list/GetMenuSortedByVisibleDescUseCase.kt
Remove this file

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/main/java/com/bunbeauty/domain/use_case/GetMenuProductUseCase.kt
> +            ?: throw Exception("")
Add more suitable Exception or message

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/main/java/com/bunbeauty/domain/exception/updateproduct/MenuProductDescriptionException.kt
> +object MenuProductDescriptionException : Exception()
replace `object` with a `class`

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/main/java/com/bunbeauty/domain/exception/updateproduct/MenuProductNameException.kt
> +object MenuProductNameException : Exception()
replace `object` with a `class`

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/main/java/com/bunbeauty/domain/exception/updateproduct/MenuProductNewPriceException.kt
> +object MenuProductNewPriceException : Exception()
replace `object` with a `class`

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/test/java/com/bunbeauty/domain/GetMenuUseCaseTest.kt
> +class GetMenuUseCaseTest {
Update this test or remove it

2023-08-15 21:31 UTC, MaxAstin commented on domain/src/test/java/com/bunbeauty/domain/UpdateMenuProductUseCaseTest.kt
> +class UpdateMenuProductUseCaseTest {
Update this test or remove it

2023-08-15 21:31 UTC, MaxAstin commented on presentation/build.gradle.kts
> +    implementation(DataStore.dataStorePreferences)
DataStore to presentation layer?

2023-08-15 21:31 UTC, MaxAstin commented on presentation/src/main/java/com/bunbeauty/presentation/view_model/menu/edit_menu_product/EditMenuProductViewModel.kt
> +                            nutrition = mutableState.value.nutrition.toIntOrNull(),
Null nutrition will not update value, lets also add `?: 0` and make a rework on backend

2023-08-15 21:31 UTC, MaxAstin commented on presentation/src/main/res/values/strings.xml
> +    <string name="error_edit_menu_product_empty_description">Описание не может быть пустым</string>
Move everything possible to the app module

2023-08-16 12:25 UTC, xidealo commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/menu/EditMenuProductFragment.kt
> +            LoadingButton(
?

2023-08-16 12:26 UTC, xidealo commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/menu/EditMenuProductFragment.kt
> +            LoadingButton(
need help with flag

2023-08-16 12:31 UTC, xidealo commented on domain/src/main/java/com/bunbeauty/domain/exception/updateproduct/MenuProductDescriptionException.kt
> +object MenuProductDescriptionException : Exception()
?

2023-08-16 12:31 UTC, xidealo commented on domain/src/main/java/com/bunbeauty/domain/exception/updateproduct/MenuProductNameException.kt
> +object MenuProductNameException : Exception()
?

2023-08-21 19:42 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/menu/MenuViewModel.kt
>  class MenuViewModel @Inject constructor(
I guess it's time to move this VM to ` :presentation`

2023-08-21 19:53 UTC, MaxAstin requested changes

2023-08-21 19:53 UTC, MaxAstin commented on presentation/src/main/java/com/bunbeauty/presentation/feature/order/mapper/OrderProductMapper.kt
> +            title = orderProduct.name + "\n" + (orderProduct.comboDescription ?: ""),
Let's add a second line only if `comboDescription` is not null or empty

2023-08-24 19:59 UTC, merged