feature/refactoring statistic
xidealo/FoodDeliveryAdmin pull request #28
Opened 2024-03-30 12:06 UTC by xidealo

2024-04-26 21:02 UTC, MaxAstin requested changes

2024-05-01 20:59 UTC, xidealo commented on data/src/main/java/com/bunbeauty/data/repository/AdditionGroupRepository.kt
> +    override suspend fun clearCache() {
yep

2024-05-01 20:59 UTC, xidealo commented on data/src/main/java/com/bunbeauty/data/repository/AdditionRepository.kt
> +        TODO("Not yet implemented")
in Vanya's feature

2024-05-05 13:31 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/additiongrouplist/AdditionGroupListFragment.kt
> +    companion object {
No need for `companion object`

2024-05-05 13:32 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/additiongrouplist/AdditionGroupListFragment.kt
> +                    items(state.hiddenAdditionItems) { hiddenAddition ->
keys

2024-05-05 13:52 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/statistic/ui/StatisticFragment.kt
> +            items(items = statisticViewState.statisticList) { statisticItemModel ->
keys

2024-05-05 13:53 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/additiongrouplist/AdditionGroupListFragment.kt
> +            is AdditionGroupList.Event.OnAdditionClick -> {
OnAdditionGroupClick

2024-05-05 13:55 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/statistic/ui/StatisticFragment.kt
> +    @Preview
showSystemUi = true

2024-05-05 13:57 UTC, MaxAstin commented on data/src/main/java/com/bunbeauty/data/repository/AdditionGroupRepository.kt
> +    override suspend fun clearCache() {
no

2024-05-07 21:22 UTC, MaxAstin approved these changes

2024-05-08 16:17 UTC, merged