feature/add menu product
xidealo/FoodDeliveryAdmin pull request #30
Opened 2024-05-09 21:10 UTC by xidealo

2024-05-13 20:53 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/gallery/GalleryFragment.kt
> +                            key = { photoLink ->
In this case we can use just `items(state.photos) { ... }` without key. It compares elements by default.

2024-05-13 20:55 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/gallery/GalleryViewState.kt
> +    val photos: List<String>,
`ImmutableList`

2024-05-13 20:59 UTC, MaxAstin commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/menulist/MenuListFragment.kt
> +                            findNavController().navigateSafe(MenuListFragmentDirections.toCreateMenuProductFragment())
action + event

2024-05-13 21:31 UTC, MaxAstin commented on presentation/src/test/java/com/bunbeauty/presentation/EditMenuProductViewModelTest.kt
> +                    com.bunbeauty.presentation.feature.menulist.editmenuproduct.EditMenuProductEvent.ShowUpdateProductError(
import

2024-05-13 21:32 UTC, MaxAstin commented on data/src/main/java/com/bunbeauty/data/repository/CategoryRepository.kt
> +    override suspend fun fetchCategories(token: String, companyUuid: String): List<Category> {
Let's add cache,
`getCategoryList` method should check cache and then go to server
`getCategoryListFromRemote` method should go to server

2024-05-13 21:34 UTC, MaxAstin requested changes
pls fix comments

2024-05-13 21:43 UTC, xidealo commented on app/src/main/java/com/bunbeauty/fooddeliveryadmin/screen/menulist/MenuListFragment.kt
> +                            findNavController().navigateSafe(MenuListFragmentDirections.toCreateMenuProductFragment())
this is old screen without actions

2024-05-15 19:51 UTC, MaxAstin approved these changes

2024-05-16 18:53 UTC, merged